### ISSUE TITLE
using <component> tag doesn't redraw the component.

### ISSUE THREAD

**Issue by johnwebbcole** [lyonlai/blessed-vue#3]
Hey,
  Love the library, thanks.  I've been using it for a command line application on a Raspberry Pi and a PiTft screen.  

  I'm trying to put in a basic router using `<component :is="componentname"></component>` syntax, but when changing `this.componentname`, it doesn't draw the new component.  The initial component does draw though.

  I tried this.$refs.screen.redraw() to no avail.  Is there something I can do to force a redraw after switching the component?

Thanks!

**Comment by lyonlai** [comment]
Sorry for the late reply. lately've been under the pump for different things. @johnwebbcole , Can you put up a demo jsfiddle so that I can have a look too?

**Comment by geiseri** [comment]
Actually now it looks like components just do not work.  The initial screen will load, but any time `:is="componentName"` is changed you get a stack trace:
```
Error: Element (box) was not appended synchronously after the screen's creation. Please set a `parent` or `screen` option in the element's constructor if you are going to use multiple screens and append the element later.
    at /home/geiseri/Nextcloud/Projects/appliance-console/node_modules/blessed/lib/widgets/node.js:48:17
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
I wonder if components changed internally since 2.3.x so that parents are not correctly being propagated.  I am looking into this now.

**Comment by geiseri** [comment]
I _think_ I found the issue.  In `src/runtime/node-ops.js:18` We assume the parent node is actually one of our own.  If `vnode.elm` is null or undefined it looks like the code in `node_modules/blessed/lib/widgets/node.js:37` will start looking for screens.  I am not sure why it cannot find one though. Not 100% sure on this because I am not clear on how Vue handles createElement internally.  I think what we need to do is make sure that `vnode.elm` is defined, and not null before setting it as the parent.  I am not sure this explains why the first component works though and subsequent ones fail. I am going to see if I can build a test case here. @lyonlai does any of this give you any hints?

**Comment by geiseri** [comment]
Okay, I can say in confidence that in `src/runtime/node-ops.js:18` `vnode.elm` is always undefined.  This is normally not a problem because in most cases the widget is added right after so `node_modules/blessed/lib/widgets/node.js:45` is satisfied.  In the case of a component it is not actually appended until its needed. (or so it seems)  This means that with no parent set the node creation itself fails.  Now how to get around this... no clue.  Is there a way we can make it parented to the screen and then when its appended as normal then it will appear?  I think we would need to play with "visible" too, again I am not sure how that would work out though.

**Comment by lyonlai** [comment]
Got a smalll sample handy? @geiseri

**Comment by geiseri** [comment]
I have it in my fork under: `./examples/components`.  Right now it crashes when you press `F2`.

**Comment by lyonlai** [comment]
Thanks @geiseri I'll take a look

**Comment by lyonlai** [comment]
@johnwebbcole & @geiseri I've got this in 2.0.1. try it out. Oh. btw the dashboard component is updated with `<compomnent :is="" />` example.

**Comment by geiseri** [comment]
Works like a dream!  Thanks!
